uploads = []
generated = []

[[outputs]]
id = "N0ygR-KPkeJMpUAT0YfIY"
uri = "file://tools/signing-agent/installer/dist/SigningAgent-Setup-0.2.0.zip"
type = "unspecified"
title = "SigningAgent-Setup-0.2.0.zip"

[[outputs]]
id = "jq_c2je2qJlLNz-fNcIbQ"
uri = "file://tools/signing-agent/installer/dist/SigningAgent-Setup-0.2.0-pades.zip"
type = "unspecified"
title = "SigningAgent-Setup 0.2.0 (PAdES)"

[[outputs]]
id = "1r64g_Fmnno0yEKQc9c7U"
uri = "file://tools/signing-agent/installer/dist/SigningAgent-Setup-0.2.1-pades.zip"
type = "unspecified"
title = "SigningAgent-Setup 0.2.1"

[[outputs]]
id = "zt261TKOb5pdy1I_avWIf"
uri = "file://tools/signing-agent/installer/dist/SigningAgent-Setup-0.2.2-rdp.zip"
type = "unspecified"
title = "SigningAgent-Setup 0.2.2 (RDP/VDI fix)"

[[outputs]]
id = "FzQ5qo_KeWvlAY9iaL5dA"
uri = "file://tools/signing-agent/installer/dist/SigningAgent-Setup-0.2.3-rdp.zip"
type = "unspecified"
title = "SigningAgent-Setup 0.2.3"

[[outputs]]
id = "3eDj8qtuG8KsWJC1REA7A"
uri = "file://tools/signing-agent/installer/dist/SigningAgent-Setup-0.2.4-cert-picker.zip"
type = "unspecified"
title = "SigningAgent-Setup-0.2.4-cert-picker.zip"

[[outputs]]
id = "rPd1xkCLkqoK4SKetNoAy"
uri = "file://tools/signing-agent/installer/dist/SigningAgent-Setup-0.2.5-env-fix.zip"
type = "unspecified"
title = "SigningAgent-Setup-0.2.5 (env fix)"

[[outputs]]
id = "XlaKbNaLir8MxtIwRb5eW"
uri = "file://tools/signing-agent/installer/dist/SigningAgent-Setup-0.2.6-key-check.zip"
type = "unspecified"
title = "SigningAgent-Setup-0.2.6 (cert key check)"

[[outputs]]
id = "xdSR5NqNLy6t02gWb8ux8"
uri = "file://tools/signing-agent/installer/dist/SigningAgent-Setup-0.2.7-fixes.zip"
type = "unspecified"
title = "SigningAgent-Setup-0.2.7 (2 bugs fixes)"
