# Generate a .env file (next to docker-compose.yml) with a random
# SESSION_SECRET if one doesn't already exist. Safe to run repeatedly:
# it never overwrites an existing .env.
$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $root ".env"

if (Test-Path $envFile) {
    Write-Host ".env already exists at $envFile -- leaving it untouched."
    exit 0
}

$bytes = New-Object byte[] 32
[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
$secret = ([BitConverter]::ToString($bytes) -replace '-','').ToLower()

$timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$content = @"
# Auto-generated by scripts/setup-env.ps1 on $timestamp
# Keep this file out of version control.
SESSION_SECRET=$secret
"@

# ASCII / no BOM so docker-compose interpolation is happy.
[System.IO.File]::WriteAllText($envFile, $content, [System.Text.Encoding]::ASCII)

Write-Host "Wrote $envFile with a fresh 64-char SESSION_SECRET."
