#!/usr/bin/env bash
# Generate a .env file (next to docker-compose.yml) with a random
# SESSION_SECRET if one doesn't already exist. Safe to run repeatedly:
# it never overwrites an existing .env.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"

if [ -f "$ENV_FILE" ]; then
  echo ".env already exists at $ENV_FILE — leaving it untouched."
  exit 0
fi

if command -v openssl >/dev/null 2>&1; then
  SECRET="$(openssl rand -hex 32)"
elif command -v node >/dev/null 2>&1; then
  SECRET="$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")"
else
  echo "Neither openssl nor node is available; cannot generate a secret." >&2
  exit 1
fi

umask 077
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/setup-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file out of version control.
SESSION_SECRET=$SECRET
EOF

echo "Wrote $ENV_FILE with a fresh 64-char SESSION_SECRET."
