# Generate a .env file (next to docker-compose.yml) with independent random
# SESSION_SECRET and SETTINGS_ENCRYPTION_KEY values. Safe to run repeatedly:
# it never overwrites an existing .env.
$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $root ".env"

if (Test-Path $envFile) {
    Write-Host ".env already exists at $envFile -- leaving it untouched."
    exit 0
}

function New-HexSecret {
    $bytes = New-Object byte[] 32
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($bytes)
    } finally {
        $rng.Dispose()
    }
    return ([BitConverter]::ToString($bytes) -replace '-','').ToLower()
}

$sessionSecret = New-HexSecret
$settingsKey = New-HexSecret
if ($sessionSecret -eq $settingsKey) {
    throw "Generated secrets unexpectedly match."
}

$timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$content = @"
# Auto-generated by scripts/setup-env.ps1 on $timestamp
# Keep this file out of version control.
SESSION_SECRET=$sessionSecret
SETTINGS_ENCRYPTION_KEY=$settingsKey
"@

# ASCII / no BOM so docker-compose interpolation is happy.
[System.IO.File]::WriteAllText($envFile, $content, [System.Text.Encoding]::ASCII)

$sessionSecret = $null
$settingsKey = $null
Write-Host "Wrote $envFile with independent 64-char session and settings keys."
