#!/usr/bin/env bash
# Generate a .env file (next to docker-compose.yml) with independent random
# SESSION_SECRET and SETTINGS_ENCRYPTION_KEY values. Safe to run repeatedly:
# it never overwrites an existing .env.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"

if [ -f "$ENV_FILE" ]; then
  echo ".env already exists at $ENV_FILE — leaving it untouched."
  exit 0
fi

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  elif command -v node >/dev/null 2>&1; then
    node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
  else
    echo "Neither openssl nor node is available; cannot generate secrets." >&2
    exit 1
  fi
}

SESSION_VALUE="$(generate_secret)"
SETTINGS_VALUE="$(generate_secret)"
[ "$SESSION_VALUE" != "$SETTINGS_VALUE" ] || {
  echo "Generated secrets unexpectedly match; aborting." >&2
  exit 1
}

umask 077
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/setup-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file out of version control.
SESSION_SECRET=$SESSION_VALUE
SETTINGS_ENCRYPTION_KEY=$SETTINGS_VALUE
EOF

unset SESSION_VALUE SETTINGS_VALUE
echo "Wrote $ENV_FILE with independent 64-char session and settings keys."
